// Generated by GitHub Copilot
// ============================================================
// Tiny backend for the "Requirements Board" on indexKZ.html.
// It has ONE job: take a requirement typed on the board, add it
// as a ticket in website/indexKZ.html, then git commit + push.
// Jenkins (Poll SCM) then picks up the push and deploys.
//
// Uses only Node's built-in modules — nothing to install.
// Run it with:  node server.js
// ============================================================

const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFile } = require('child_process');

const PORT = 3000;
const REPO = __dirname;                                     // repo root (this file lives here)
const INDEX = path.join(REPO, 'website', 'indexKZ.html');   // board page we edit

// Shared secret that locks the endpoint. Read from the environment so it
// is NEVER hardcoded or committed. Set it before starting:
//   Linux/EC2:  export BOARD_SECRET='your-passphrase'
//   PowerShell: $env:BOARD_SECRET = 'your-passphrase'
// If unset, the server refuses to start (fail closed).
const BOARD_SECRET = process.env.BOARD_SECRET;

// Constant-time compare so an attacker can't guess the secret by timing.
function secretMatches(provided) {
    if (typeof provided !== 'string' || provided.length === 0) { return false; }
    const a = Buffer.from(provided);
    const b = Buffer.from(BOARD_SECRET);
    if (a.length !== b.length) { return false; }
    return crypto.timingSafeEqual(a, b);
}

// Escape user text so it can't inject HTML/JS (XSS protection).
function escapeHtml(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Run git safely: execFile uses an args array (no shell), so the
// requirement text can never be interpreted as a shell command.
function git(args) {
    return new Promise((resolve, reject) => {
        execFile('git', ['-C', REPO, ...args], (err, stdout, stderr) => {
            if (err) { reject(new Error(stderr || err.message)); }
            else { resolve(stdout.trim()); }
        });
    });
}

// Insert a new ticket into the board in indexKZ.html, right before the
// <!-- new-cards --> marker, so it lands inside the board column.
function addCard(requirement) {
    const html = fs.readFileSync(INDEX, 'utf8');
    const safe = escapeHtml(requirement);

    // Generated by GitHub Copilot
    const card =
`                    <div class="ticket">
                        <span class="ticket-tag">Requirement</span>
                        <p>${safe}</p>
                    </div>
                    <!-- new-cards -->`;

    // Insert before the marker so the ticket joins the board.
    const marker = '<!-- new-cards -->';
    if (!html.includes(marker)) { throw new Error('Could not find the board marker in indexKZ.html.'); }
    const updated = html.replace(marker, card);
    fs.writeFileSync(INDEX, updated, 'utf8');
}

// Handle CORS so board.html (served from any port) can call this.
function setCors(res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Board-Secret');
}

const server = http.createServer((req, res) => {
    setCors(res);

    if (req.method === 'OPTIONS') { res.writeHead(204).end(); return; }

    if (req.method === 'POST' && req.url === '/api/requirement') {
        // Lock: reject anyone who doesn't send the correct secret header.
        if (!secretMatches(req.headers['x-board-secret'])) {
            res.writeHead(401, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ ok: false, error: 'Unauthorized: wrong or missing passphrase.' }));
            return;
        }
        let body = '';
        req.on('data', chunk => {
            body += chunk;
            if (body.length > 5000) { req.destroy(); }  // reject oversized input
        });
        req.on('end', async () => {
            try {
                const { requirement } = JSON.parse(body || '{}');
                // Validate at the boundary: must be a short, non-empty string.
                if (!requirement || typeof requirement !== 'string' || requirement.trim().length === 0) {
                    res.writeHead(400, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ ok: false, error: 'Requirement is empty.' }));
                    return;
                }
                const text = requirement.trim().slice(0, 500);

                addCard(text);
                await git(['add', 'website/indexKZ.html']);
                await git(['commit', '-m', 'Add requirement from board']);
                await git(['push']);

                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ ok: true, message: 'Pushed! Jenkins will deploy it shortly.' }));
            } catch (e) {
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ ok: false, error: e.message }));
            }
        });
        return;
    }

    res.writeHead(404).end('Not found');
});

// Fail closed: don't run an unlocked endpoint that can push to the repo.
if (!BOARD_SECRET || BOARD_SECRET.length < 8) {
    console.error('Refusing to start: set BOARD_SECRET (>= 8 chars) first.');
    console.error("  Linux/EC2:  export BOARD_SECRET='your-passphrase'");
    console.error("  PowerShell: $env:BOARD_SECRET = 'your-passphrase'");
    process.exit(1);
}

server.listen(PORT, () => {
    console.log(`Requirements Board backend running at http://localhost:${PORT}`);
    console.log('Locked: submissions require the correct passphrase.');
});
