// Generated by GitHub Copilot
// ============================================================
// Tiny local backend for the "Requirements Board".
// It has ONE job: take a requirement typed in board.html, add it
// as a card in website/index.html, then git commit + push.
// Jenkins (Poll SCM) then picks up the push and deploys.
//
// Uses only Node's built-in modules — nothing to install.
// Run it with:  node server.js
// ============================================================

const http = require('http');
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

const PORT = 3000;
const REPO = __dirname;                                   // repo root (this file lives here)
const INDEX = path.join(REPO, 'website', 'index.html');   // page we edit

// Escape user text so it can't inject HTML/JS (XSS protection).
function escapeHtml(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Run git safely: execFile uses an args array (no shell), so the
// requirement text can never be interpreted as a shell command.
function git(args) {
    return new Promise((resolve, reject) => {
        execFile('git', ['-C', REPO, ...args], (err, stdout, stderr) => {
            if (err) { reject(new Error(stderr || err.message)); }
            else { resolve(stdout.trim()); }
        });
    });
}

// Insert a new card into index.html right before the <!-- new-cards -->
// marker, so cards land inside the requirements section (never the hero).
function addCard(requirement) {
    const html = fs.readFileSync(INDEX, 'utf8');
    const safe = escapeHtml(requirement);

    // Generated by GitHub Copilot
    const card =
`            <div class="card">
                <h3>Requirement</h3>
                <p>${safe}</p>
            </div>
            <!-- new-cards -->`;

    // Insert before the marker so the card joins the requirements grid.
    const marker = '<!-- new-cards -->';
    if (!html.includes(marker)) { throw new Error('Could not find the requirements marker in index.html.'); }
    const updated = html.replace(marker, card);
    fs.writeFileSync(INDEX, updated, 'utf8');
}

// Handle CORS so board.html (served from any port) can call this.
function setCors(res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

const server = http.createServer((req, res) => {
    setCors(res);

    if (req.method === 'OPTIONS') { res.writeHead(204).end(); return; }

    if (req.method === 'POST' && req.url === '/api/requirement') {
        let body = '';
        req.on('data', chunk => {
            body += chunk;
            if (body.length > 5000) { req.destroy(); }  // reject oversized input
        });
        req.on('end', async () => {
            try {
                const { requirement } = JSON.parse(body || '{}');
                // Validate at the boundary: must be a short, non-empty string.
                if (!requirement || typeof requirement !== 'string' || requirement.trim().length === 0) {
                    res.writeHead(400, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ ok: false, error: 'Requirement is empty.' }));
                    return;
                }
                const text = requirement.trim().slice(0, 500);

                addCard(text);
                await git(['add', 'website/index.html']);
                await git(['commit', '-m', 'Add requirement from board']);
                await git(['push']);

                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ ok: true, message: 'Pushed! Jenkins will deploy it shortly.' }));
            } catch (e) {
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ ok: false, error: e.message }));
            }
        });
        return;
    }

    res.writeHead(404).end('Not found');
});

server.listen(PORT, () => {
    console.log(`Requirements Board backend running at http://localhost:${PORT}`);
    console.log('Leave this window open. Submit requirements from board.html.');
});
