jenkins:
  systemMessage: "Practical Task Jenkins"

  securityRealm:
    none

  authorizationStrategy:
    unsecured: {}

unclassified:
  location:
    url: "http://localhost:8080/"

jobs:
  - file: /var/lib/jenkins/casc/jobs.groovy